server:
  port: 8080

moorse:
  integration: e60da7c0-6c7a-46f6-b05d-05247b37240e
  api:
    url: https://api.moorse.io/
  token: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkb3VnbGFzLmFsdmVzQGNjYy51ZmNnLmVkdS5iciIsImlkQ2xpZW50IjoiZmFkODk4OTYtMmY1Ny00YTc4LWIyMTEtZTgyNTUyMDdiZWRmIiwiY3JlYXRlZCI6MTY0MTQwMDk0MDQ3MSwicm9sZXMiOlsiUk9MRV9BUEkiLCJST0xFX0RBU0hCT0FSRCIsIlJPTEVfREFTSEJPQVJEX0dST1VQUyIsIlJPTEVfR1JPVVBTIiwiUk9MRV9JTlRFR1JBVElPTl9VU0VSIiwiUk9MRV9UUklBTCIsIlJPTEVfVVNFUlMiLCJST0xFX1dFQkhPT0siXSwiaWQiOjIzNywiZXhwIjoxNjcyOTM2OTQwfQ.o4qeTqq8eA2jPZf7LFKH1lfWqhbY7-xT4VPDxFmMJRygwguZ9GW8KlnJIUB2lVRxy__lFPGpLSLg0jigfhRWlw